User.create(username: "jezebel", password:"jezebel", email:"heathen@feminist.com")
User.create(username: "calvin", password:"hobbes", email:"calvin@hobbes.edu")
User.create(username: "the_dream", password:"terius", email:"the_dream@richandfamous.info")
User.create(username: "katy", password:"perry", email:"waking@vegas.museum")
User.create(username: "channing_tatum", password:"muscles", email:"hotbody@sexymales.org")

Url.create(long: "http://xkcd.com", short: "xkcd", user_id: 2)
Url.create(long: "http://xojane.com", short: "xoj", user_id: 5)
Url.create(long: "http://valleywag.gawker.com", short: "filth", user_id: 5)
Url.create(long: "http://notcot.org", short: "art", user_id: 2)
Url.create(long: "http://google.com", short: "find", user_id: 5)
